version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/FL.DriveMapper"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    groups:
      nuget-minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      actions-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
